const students = [
  { name: "Aarav Sharma", isPresent: true },
  { name: "Ananya Verma", isPresent: true },
  { name: "Rohan Singh", isPresent: true },
  { name: "Priya Patel", isPresent: true },
  { name: "Aditya Gupta", isPresent: true },
  { name: "Sneha Mishra", isPresent: true },
  { name: "Karan Yadav", isPresent: true },
  { name: "Neha Joshi", isPresent: true },
  { name: "Vivek Kumar", isPresent: true },
  { name: "Pooja Nair", isPresent: true },
  { name: "Rahul Mehta", isPresent: true },
  { name: "Ishita Roy", isPresent: true },
  { name: "Arjun Kapoor", isPresent: true },
  { name: "Simran Kaur", isPresent: true },
  { name: "Harsh Agarwal", isPresent: true },
  { name: "Meera Iyer", isPresent: true },
  { name: "Yash Thakur", isPresent: true },
  { name: "Nikita Sinha", isPresent: true },
  { name: "Siddharth Jain", isPresent: true },
  { name: "Kavya Reddy", isPresent: true },
  { name: "Manav Choudhary", isPresent: true },
  { name: "Aditi Saxena", isPresent: true },
  { name: "Lakshya Bansal", isPresent: true },
  { name: "Tanvi Kulkarni", isPresent: true },
  { name: "Dev Malhotra", isPresent: true },
];

export { students };
